import 'package:flutter/material.dart';

// Imports for Firebase
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is the file generated by the FlutterFire CLI

Future<void> main() async {
  // These two lines are the new core initialization code
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Movie Tracker'),
        ),
        body: const Center(
          child: Text('Firebase Initialized!'),
        ),
      ),
    );
  }
}